name: New Post
run-name: Create ${{ inputs.filename }}

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'Filename'
        required: true
        default: 'new.md'

jobs:
  new_page:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Create
        run: hugo new posts/${{ inputs.filename }}

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4